# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: TeamCity
website: http://tiny.cc/EssentialsCommands
description: Provides an essential, core set of commands for Bukkit.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally]
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command> [player]
    aliases: [eafk]
  antioch:
    description: 'A little surprise for operators.'
    usage: /<command> [message]
    aliases: [eantioch,grenade,egrenade,tnt,etnt]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command>
    aliases: [eback,return,ereturn]
  backup:
    description: Runs the backup if configured.
    usage: /<command>
    aliases: [ebackup]
  balance:
    description: States the current balance of a player.
    usage: /<command> [player]
    aliases: [bal,ebal,ebalance,money,emoney]
  balancetop:
    description: Gets the top balance values.
    usage: /<command> <page>
    aliases: [ebalancetop,baltop,ebaltop]
  ban:
    description: Bans a player.
    usage: /<command> <player> [reason]
    aliases: [eban]
  banip:
    description: Bans an IP address.
    usage: /<command> <address>
    aliases: [ebanip]
  book:
    description: Allows reopening and editing of sealed books.
    usage: /<command> [title|author [name]]
    aliases: [ebook]
  break:
    description: Breaks the block you are looking at.
    usage: /<command>
    aliases: [ebreak]
  broadcast:
    description: Broadcasts a message to the entire server.
    usage: /<command> <msg>
    aliases: [bc,ebc,bcast,ebcast,ebroadcast,shout,eshout]
  bigtree:
    description: Spawn a big tree where you are looking.
    usage: /<command> <tree|redwood|jungle>
    aliases: [ebigtree]
  burn:
    description: Set a player on fire.
    usage: /<command> <player> <seconds>
    aliases: [eburn]
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command> [<player> [item]]
    aliases: [ci,eci,clean,eclean,clear,eclear,clearinvent,eclearinvent,eclearinventory]
  compass:
    description: Describes your current bearing.
    usage: /<command>
    aliases: [ecompass,direction,edirection]
  delhome:
    description: Removes a home.
    usage: /<command> [player:]<name>
    aliases: [edelhome,remhome,eremhome,rmhome,ermhome]
  deljail:
    description: Removes a jail.
    usage: /<command> <jailname>
    aliases: [edeljail]
  delwarp:
    description: Deletes the specified warp.
    usage: /<command> <warp>
    aliases: [edelwarp,remwarp,eremwarp,rmwarp,ermwarp]
  depth:
    description: States current depth, relative to sea level.
    usage: /depth
    aliases: [edepth]
  eco:
    description: Manages the server economy.
    usage: /<command> <give|take|set|reset> <player> <amount>
    aliases: [eeco,economy,eeconomy]
  enchant:
    description: Enchants the item the user is holding.
    usage: /<command> <enchantmentname> [level]
    aliases: [eenchant,enchantment,eenchantment]
  enderchest:
    description: Lets you see inside an enderchest.
    usage: /<command> [player]
    aliases: [echest,eechest,eenderchest,endersee,eendersee]
  essentials:
    description: Reloads essentials.
    usage: /<command>
    aliases: [ess]
  exp:
    description: Give, set or look at a players exp.
    usage: /<command> [show|set|give] [playername [amount]]
    aliases: [eexp,xp]
  ext:
    description: Extinguish players.
    usage: /<command> [player]
    aliases: [eext,extinguish,eextinguish]
  feed:
    description: Satisfy the hunger.
    usage: /<command> [player]
    aliases: [eat,eeat,efeed]
  fly:
    description: Take off, and soar!
    usage: /<command> [player [on|off]]
    aliases: [efly]
  fireball:
    description: Throw a fireball.
    usage: /<command> [small|skull]
    aliases: [efireball,fireentity,efireentity,fireskull,efireskull]
  firework:
    description: Allows you to modify a stack of fireworks.
    usage: /<command> <<meta param>|power [amount]|clear|fire [amount]>
    aliases: [efirework]
  gamemode:
    description: Change player gamemode.
    usage: /<command> <survival|creative|adventure> [player]
    aliases: [adventure,eadventure,adventuremode,eadventuremode,creative,eecreative,creativemode,ecreativemode,egamemode,gm,egm,gma,egma,gmc,egmc,gms,egms,gmt,egmt,survival,esurvival,survivalmode,esurvivalmode]
  gc:
    description: Reports memory, uptime and tick info.
    usage: /<command> [all]
    aliases: [lag,elag,egc,mem,emem,memory,ememory,uptime,euptime]
  getpos:
    description: Get your current coordinates or those of a player.
    usage: /<command> [player]
    aliases: [coords,egetpos,position,eposition,whereami,ewhereami]
  give:
    description: Give a player an item.
    usage: /<command> <player> <item|numeric> [amount <enchantmentname[:level]> ...]
    aliases: [egive]
  god:
    description: Enables your godly powers.
    usage: /<command> [player [on|off]]
    aliases: [egod,godmode,egodmode,tgm,etgm]
  hat:
    description: Get some cool new headgear.
    usage: /<command> [remove]
    aliases: [ehat]
  heal:
    description: Heals you or the given player.
    usage: /<command> [player]
    aliases: [eheal]
  help:
    description: Views a list of available commands.
    usage: /<command> [search term] [page]
    aliases: [ehelp]
  helpop:
    description: Message online admins.
    usage: /<command> <message>
    aliases: [ac,eac,amsg,eamsg,ehelpop]
  home:
    description: Teleport to your home.
    usage: /<command> [player:][name]
    aliases: [ehome,homes,ehomes]
  ignore:
    description: Ignore other players.
    usage: /<command> <player>
    aliases: [eignore]
  info:
    description: Shows information set by the server owner.
    usage: /<command> [chapter] [page]
    aliases: [about,eabout,ifo,eifo,einfo,inform,einform,news,enews]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
    aliases: [einvsee]
  item:
    description: Spawn an item.
    usage: /<command> <item|numeric> [amount <enchantmentname[:level]> ...]
    aliases: [i,eitem]
  itemdb:
    description: Searches for an item.
    usage: /<command> <item>
    aliases: [dura,edura,durability,edurability,eitemdb,itemno,eitemno]
  jails:
    description: List all jails.
    usage: /<command>
    aliases: [ejails]
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: [j,ej,ejump,jumpto,ejumpto]
  kick:
    description: Kicks a specified player with a reason.
    usage: /<command> <player> [reason]
    aliases: [ekick]
  kickall:
    description: Kicks all players off the server except the issuer.
    usage: /<command> [reason]
    aliases: [ekickall]
  kill:
    description: Kills specified player.
    usage: /<command> <player>
    aliases: [ekill]
  killall:
    description: Kill all mobs in a world.
    usage: /<command> [mobType] [radius]
    aliases: [butcher,ebutcher,ekillall,mobkill,emobkill]
  kit:
    description: Obtains the specified kit or views all available kits.
    usage: /<command> [kit] [player]
    aliases: [ekit,kits,ekits]
  kittycannon:
    description: Throw an exploding kitten at your opponent.
    usage: /<command>
  lightning:
    description: The power of Thor. Strike at cursor or player.
    usage: /<command> [player] [power]
    aliases: [elightning,shock,eshock,smite,esmite,strike,estrike,thor,ethor]
  list:
    description: List all online players.
    usage: /<command>
    aliases: [elist,online,eonline,playerlist,eplayerlist,plist,eplist,who,ewho]
  mail:
    description: Manages inter-player, intra-server mail.
    usage: /<command> [read|clear|send [to] [message]|sendall [message]]
    aliases: [email]
  me:
    description: Describes an action in the context of the player.
    usage: /<command> <description>
    aliases: [action,eaction,describe,edescribe,eme]
  more:
    description: Fills the item stack in hand to maximum size.
    usage: /<command>
    aliases: [emore]
  motd:
    description: Views the Message Of The Day.
    usage: /<command>
    aliases: [emotd]
  msg:
    description: Sends a private message to the specified player.
    usage: /<command> <to> <message>
    aliases: [w,m,t,emsg,tell,etell,whisper,ewhisper]
  mute:
    description: Mutes or unmutes a player.
    usage: /<command> <player> [datediff]
    aliases: [emute]
  near:
    description: Lists the players near by or around a player.
    usage: /<command> [playername] [radius]
    aliases: [enear,nearby,enearby]
  nick:
    description: Change your nickname or that of another player.
    usage: /<command> [player] <nickname|off>
    aliases: [enick]
  nuke:
    description: May death rain upon them.
    usage: /<command> [player]
    aliases: [enuke]
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
    aliases: [epay]
  ping:
    description: Pong!
    usage: /<command>
    aliases: [echo,eecho,eping,pong,epong]
  powertool:
    description: Assigns a command to the item in hand.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
    aliases: [epowertool,pt,ept]
  powertooltoggle:
    description: Enables or disables all current powertools.
    usage: /<command>
    aliases: [epowertooltoggle,ptt,eptt,pttoggle,epttoggle]
  ptime:
    description: Adjust player's client time. Add @ prefix to fix.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: [playertime,eplayertime,eptime]
  r:
    description: Quickly reply to the last player to message you.
    usage: /<command> <message>
    aliases: [er,reply,ereply]
  realname:
    description: Displays the username of a user based on nick.
    usage: /<command> <nickname>
    aliases: [erealname]
  recipe:
    description: Displays how to craft items.
    usage: /<command> <item> [number]
    aliases: [formula,eformula,method,emethod,erecipe,recipes,erecipes]
  remove:
    description: Removes entities in your world.
    usage: /<command> <drops|arrows|boats|minecarts|xp|paintings> [radius]
    aliases: [eremove]
  repair:
    description: Repairs the durability of all or one item.
    usage: /<command> <hand|all>
    aliases: [fix,efix,erepair]
  rules:
    description: Views the server rules.
    usage: /<command>
    aliases: [erules]
  seen:
    description: Shows the last logout time of a player.
    usage: /<command> <playername>
    aliases: [eseen]
  sell:
    description: Sells the item currently in your hand.
    usage: /<command> <itemname|id|hand|inventory|blocks> [-][amount]
    aliases: [esell]
  sethome:
    description: Set your home to your current location.
    usage: /<command> [[player:]name]
    aliases: [esethome]
  setjail:
    description: Creates a jail where you specified named [jailname].
    usage: /<command> <jailname>
    aliases: [esetjail]
  setwarp:
    description: Creates a new warp.
    usage: /<command> <warp>
    aliases: [createwarp,ecreatewarp,esetwarp]
  setworth:
    description: Set the sell value of an item.
    usage: /<command> [itemname|id] <price>
    aliases: [esetworth]
  socialspy:
    description: Toggles if you can see msg/mail commands in chat.
    usage: /<command>
    aliases: [esocialspy]
  spawner:
    description: Change the mob type of a spawner.
    usage: /<command> <mob>
    aliases: [changems,echangems,espawner]
  spawnmob:
    description: Spawns a mob.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [player]
    aliases: [mob,emob,spawnentity,espawnentity,espawnmob]
  speed:
    description: Change your speed limits.
    usage: /<command> <speed> [player]
    aliases: [flyspeed,eflyspeed,fspeed,efspeed,espeed,walkspeed,ewalkspeed,wspeed,ewspeed]
  sudo:
    description: Make another user perform a command.
    usage: /<command> <player> <command [args]>
    aliases: [esudo]
  suicide:
    description: Causes you to perish.
    usage: /<command>
    aliases: [esuicide]
  tempban:
    description: Temporary ban a user.
    usage: /<command> <playername> <datediff>
    aliases: [etempban]
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
    aliases: [ethunder]
  time:
    description: Display/Change the world time. Defaults to current world.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [day,eday,night,enight,etime]
  togglejail:
    description: Jails/Unjails a player, TPs them to the jail specified.
    usage: /<command> <player> <jailname> [datediff]
    aliases: [jail,ejail,tjail,etjail,etogglejail,unjail,eunjail]
  top:
    description: Teleport to the highest block at your current position.
    usage: /<command>
    aliases: [etop]
  tp:
    description: Teleport to a player.
    usage: /<command> <player> [otherplayer]
    aliases: [tele,etele,teleport,eteleport,etp,tp2p,etp2p]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
    aliases: [call,ecall,etpa,tpask,etpask]
  tpaall:
    description: Requests all players online to teleport to you.
    usage: /<command> <player>
    aliases: [etpaall]
  tpaccept:
    description: Accepts a teleport request.
    usage: /<command> [otherplayer]
    aliases: [etpaccept,tpyes,etpyes]
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
    aliases: [etpahere]
  tpall:
    description: Teleport all online players to another player.
    usage: /<command> <player>
    aliases: [etpall]
  tpdeny:
    description: Reject a teleport request.
    usage: /<command>
    aliases: [etpdeny,tpno,etpno]
  tphere:
    description: Teleport a player to you.
    usage: /<command> <player>
    aliases: [s,etphere]
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player> [otherplayer]
    aliases: [etpo]
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
    aliases: [etpohere]
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z> [yaw] [pitch]
    aliases: [etppos]
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command> [player [on|off]]
    aliases: [etptoggle]
  tree:
    description: Spawn a tree where you are looking.
    usage: /<command> <tree|birch|redwood|redmushroom|brownmushroom|jungle|junglebush|swamp>
    aliases: [etree]
  unban:
    description: Unbans the specified player.
    usage: /<command> <player>
    aliases: [pardon,eunban,epardon]
  unbanip:
    description: Unbans the specified IP address.
    usage: /<command> <address>
    aliases: [eunbanip,pardonip,epardonip]
  unlimited:
    description: Allows the unlimited placing of items.
    usage: /<command> <list|item|clear> [player]
    aliases: [eunlimited,ul,unl,eul,eunl]
  vanish:
    description: Hide yourself from other players.
    usage: /<command> [on|off]
    aliases: [v,ev,evanish]
  warp:
    description: List all warps or warp to the specified location.
    usage: /<command> <pagenumber|warp> [player]
    aliases: [ewarp,warps,ewarps]
  weather:
    description: Sets the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [rain,erain,sky,esky,storm,estorm,sun,esun,eweather]
  whois:
    description: Determine the username behind a nickname.
    usage: /<command> <nickname>
    aliases: [ewhois]
  workbench:
    description: Opens up a workbench.
    usage: /<command>
    aliases: [craft,ecraft,wb,ewb,wbench,ewbench,eworkbench]
  world:
    description: Switch between worlds.
    usage: /<command> [world]
    aliases: [eworld]
  worth:
    description: Calculates the worth of items in hand or as specified.
    usage: /<command> [item] [amount]
    aliases: [eprice,price,eworth]

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
