name: GroupManager
version: GMBuildVer (Phoenix)
main: org.anjocaido.groupmanager.GroupManager
website: http://ess.khhq.net/wiki/Group_Manager
description: Provides on-the-fly system for permissions system created by Nijikokun. But all in memory, and with flat-file saving schedule.
authors:
  - AnjoCaido
  - Gabriel Couto
  - ElgarL
commands:
  manuadd:
    description: Moves a player to desired group (Adds to the file if does not exist).
    usage: /<command> <player> <group> | optional [world]
    permissions: groupmanager.manuadd
  manudel:
    description: Removes any user specific configuration and make them default group.
    usage: /<command> <player>
    permissions: groupmanager.manudel
  manuaddsub:
    description: Adds a group to a user's subgroup list.
    usage: /<command> <player> <group>
    permissions: groupmanager.manuaddsub
  manudelsub:
    description: Removes a group from a user's subgroup list.
    usage: /<command> <player> <group>
    permissions: groupmanager.manudelsub
  mangadd:
    description: Adds group to the system.
    usage: /<command> <group>
    permissions: groupmanager.mangadd
  mangdel:
    description: Removes a group from the system (all its users become default).
    usage: /<command> <group>
    permissions: groupmanager.mangdel
  manuaddp:
    description: Adds permissions directly to the user.
    usage: /<command> <player> <permission> [permission2] [permission3]..
    permissions: groupmanager.manuaddp
  manudelp:
    description: Removes permissions directly from the user.
    usage: /<command> <player> <permission> [permission2] [permission3]..
    permissions: groupmanager.manudelp
  manuclearp:
    description: Removes all permissions from a user.
    usage: /<command> <player>
    permissions: groupmanager.manuclearp
  manulistp:
    description: Lists all permissions of a user.
    usage: /<command> <player>
    permissions: groupmanager.manulistp
  manucheckp:
    description: Verifys if user has a permission, and where it comes from.
    usage: /<command> <player> <permissions>
    permissions: groupmanager.manucheckp
  mangaddp:
    description: Adds permissions to a group.
    usage: /<command> <group> <permission> [permission2] [permission3]..
    permissions: groupmanager.mangaddp
  mangdelp:
    description: Removes permissions from a group.
    usage: /<command> <group> <permission> [permission2] [permission3]..
    permissions: groupmanager.mangdelp
  mangclearp:
    description: Removes all permissions from a group.
    usage: /<command> <group> <permissions>
    permissions: groupmanager.mangclearp
  manglistp:
    description: Lists all permissions of a group.
    usage: /<command> <group>
    permissions: groupmanager.manglistp
  mangcheckp:
    description: Checks if group has a permission and where it comes from.
    usage: /<command> <group> <permissions>
    permissions: groupmanager.mangcheckp
  mangaddi:
    description: Adds a group to another group inheritance list.
    usage: /<command> <group1> <group2>
    permissions: groupmanager.mangaddi
  mangdeli:
    description: Removes a group from another group inheritance list.
    usage: /<command> <group1> <group2>
    permissions: groupmanager.mangdeli
  manuaddv:
    description: Adds or replaces a variable of a user (like prefix or suffix).
    usage: /<command> <user> <variable> <value>
    permissions: groupmanager.manuaddv
  manudelv:
    description: Removes a variable from a user.
    usage: /<command> <user> <variable>
    permissions: groupmanager.manudelv
  manulistv:
    description: Lists variables of a user (like prefix or suffix).
    usage: /<command> <user>
    permissions: groupmanager.manulistv
  manucheckv:
    description: Verifys a value of a variable of a user, and where it comes from.
    usage: /<command> <user> <variable>
    permissions: groupmanager.manucheckv
  mangaddv:
    description: Adds or replaces a variable of a group (like prefix or suffix).
    usage: /<command> <group> <variable> <value>
    permissions: groupmanager.mangaddv
  mangdelv:
    description: Removes a variable from a group.
    usage: /<command> <group> <variable>
    permissions: groupmanager.mangdelv
  manglistv:
    description: Lists variables of a group (like prefix or suffix).
    usage: /<command> <group>
    permissions: groupmanager.manglistv
  mangcheckv:
    description: Verifys a value of a variable of a group, and where it comes from.
    usage: /<command> <group> <variable>
    permissions: groupmanager.mangckeckv
  manwhois:
    description: Lists groups and other data of a user.
    usage: /<command> <player>
    permissions: groupmanager.manwhois
  tempadd:
    description: Creates a temporary permissions copy for a user.
    usage: /<command> <player>
    permissions: groupmanager.tempadd
  tempdel:
    description: Removes the temporary permissions copy for a user.
    usage: /<command> <player>
    permissions: groupmanager.tempdel
  templist:
    description: Lists users in overload-permissions mode made by command /tempadd.
    usage: /<command>
    permissions: groupmanager.templist
  tempdelall:
    description: Removes all overrides made by command /tempadd.
    usage: /<command>
    permissions: groupmanager.tempdelall
  mansave:
    description: Saves all permissions from server to file.
    usage: /<command>
    permissions: groupmanager.mansave
  manload:
    description: Reloads current world and config.yml, or loads given world from file to server.
    usage: /<command> [world]
    permissions: groupmanager.manload
  listgroups:
    aliases: [manlistg]
    description: Lists the groups available.
    usage: /<command>
    permissions: groupmanager.listgroups
  manpromote:
    description: Promotes a user in the same heritage line to a higher rank.
    usage: /<command> <player> <group>
    permissions: groupmanager.manpromote
  mandemote:
    description: Demotes a user in the same heritage line to a lower rank.
    usage: /<command> <player> <group>
    permissions: groupmanager.mandemote
  mantogglevalidate:
    description: Toggles on/off the validating if user is online.
    usage: /<command>
    permissions: groupmanager.mantogglevalidate
  mantogglesave:
    description: Toggles on/off the autosave.
    usage: /<command>
    permissions: groupmanager.mantogglesave
  manworld:
    description: Prints the selected world name.
    usage: /<command>
    permissions: groupmanager.manworld
  manselect:
    description: Selects a world to work with commands.
    usage: /<command> <world>
    permissions: groupmanager.manselect
  manclear:
    description: Clears world selection. Commands will work on your current world.
    usage: /<command>
    permissions: groupmanager.manclear
  mancheckw:
    description: Obtains the path to each file a world is storing its data in (users/groups).
    usage: /<command> <world>
    permissions: groupmanager.mancheckw
    
Permissions:
    groupmanager.op:
        description: User is treated as an op when using the GroupManager commands.
        default: false
