name: GroupManager
version: "1.7 (Phoenix)"
main: org.anjocaido.groupmanager.GroupManager
website: http://www.anjocaido.info/
description: Provides on-the-fly system for permissions system created by Nijikokun. But all in memory, and with flat-file saving schedule.
authors:
  - AnjoCaido
  - Gabriel Couto
commands:
  manuadd:
    description: Move a player to desired group.(Adds to the file if not exists)
    usage: /<command> <player> <group>
    permissions: groupmanager.manuadd
  manudel:
    description: Remove any user specific configuration. Make him default group.
    usage: /<command> <player>
    permissions: groupmanager.manudel
  manuaddsub:
    description: Add a group to a player's subgroup list.
    usage: /<command> <player> <group>
    permissions: groupmanager.manuaddsub
  manudelsub:
    description: Remove a group to a player's subgroup list.
    usage: /<command> <player> <group>
    permissions: groupmanager.manudelsub
  mangadd:
    description: Add group to the system.
    usage: /<command> <group>
    permissions: groupmanager.mangadd
  mangdel:
    description: Removes group from the system(all it's users become default)
    usage: /<command> <group>
    permissions: groupmanager.mangdel
  manuaddp:
    description: Add permissions diretly to the player.
    usage: /<command> <player> <permissions>
    permissions: groupmanager.manuaddp
  manudelp:
    description: Removes permissions diretly from the player.
    usage: /<command> <player> <permissions>
    permissions: groupmanager.manudelp
  manulistp:
    description: List all permissionss from a player.
    usage: /<command> <player>
    permissions: groupmanager.manulistp
  manucheckp:
    description: Verify if user has a permissions, and where it comes from.
    usage: /<command> <player> <permissions>
    permissions: groupmanager.manucheckp
  mangaddp:
    description: Add permissions to a group.
    usage: /<command> <group> <permissions>
    permissions: groupmanager.mangaddp
  mangdelp:
    description: Removes permissions from a group.
    usage: /<command> <group> <permissions>
    permissions: groupmanager.mangdelp
  manglistp:
    description: Lists all permissionss from a group.
    usage: /<command> <group>
    permissions: groupmanager.manglistp
  mangcheckp:
    description: Check if group has a permissions, and where it comes from.
    usage: /<command> <group> <permissions>
    permissions: groupmanager.mangcheckp
  mangaddi:
    description: Add a group to another group inheritance list.
    usage: /<command> <group1> <group2>
    permissions: groupmanager.mangaddi
  mangdeli:
    description: Remove a group from another group inheritance list.
    usage: /<command> <group1> <group2>
    permissions: groupmanager.mangdeli
  manuaddv:
    description: Add, or replaces, a variable to a user (like prefix or suffix).
    usage: /<command> <user> <variable> <value>
    permissions: groupmanager.manuaddv
  manudelv:
    description: Remove a variable from a user.
    usage: /<command> <user> <variable>
    permissions: groupmanager.manudelv
  manulistv:
    description: List variables a user has (like prefix or suffix).
    usage: /<command> <user>
    permissions: groupmanager.manulistv
  manucheckv:
    description: Verify a value of a variable of user, and where it comes from.
    usage: /<command> <user> <variable>
    permissions: groupmanager.manucheckv
  mangaddv:
    description: Add, or replaces, a variable to a group (like prefix or suffix).
    usage: /<command> <group> <variable> <value>
    permissions: groupmanager.mangaddv
  mangdelv:
    description: Remove a variable from a group.
    usage: /<command> <group> <variable>
    permissions: groupmanager.mangdelv
  manglistv:
    description: List variables a group has (like prefix or suffix).
    usage: /<command> <group>
    permissions: groupmanager.manglistv
  mangcheckv:
    description: Verify a value of a variable of group, and where it comes from.
    usage: /<command> <group> <variable>
    permissions: groupmanager.mangckeckv
  manwhois:
    description: Tell the group that user belongs.
    usage: /<command> <player>
    permissions: groupmanager.manwhois
  tempadd:
    description: Creates a temporary permissions copy for that user.
    usage: /<command> <player>
    permissions: groupmanager.tempadd
  tempdel:
    description: Remove the temporary permissions copy for player.
    usage: /<command> <player>
    permissions: groupmanager.tempdel
  templist:
    description: List players in overload-permissionss mode made by /tempadd.
    usage: /<command>
    permissions: groupmanager.templist
  tempdelall:
    description: Remove all overrides made by command /tempadd.
    usage: /<command>
    permissions: groupmanager.tempdelall
  mansave:
    description: Save all permissionss on file.
    usage: /<command>
    permissions: groupmanager.mansave
  manload:
    description: Reload current world and config.yml. Or load given world.
    usage: /<command> [world]
    permissions: groupmanager.manload
  listgroups:
    description: List the groups available.
    usage: /<command>
    permissions: groupmanager.listgroups
  manpromote:
    description: Promote a player in the same heritage line to a higher rank.
    usage: /<command> <player> <group>
    permissions: groupmanager.manpromote
  mandemote:
    description: Demote a player in the same heritage line to a lower rank.
    usage: /<command> <player> <group>
    permissions: groupmanager.mandemote
  mantogglevalidate:
    description: Toggle on/off the validating if player is online.
    usage: /<command>
    permissions: groupmanager.mantogglevalidate
  mantogglesave:
    description: Toggle on/ff the autosave.
    usage: /<command>
    permissions: groupmanager.mantogglesave
  manworld:
    description: Prints the selected world name
    usage: /<command>
    permissions: groupmanager.manworld
  manselect:
    description: Select a world to work with next commands.
    usage: /<command> <world>
    permissions: groupmanager.manselect
  manclear:
    description: Clear world selection. Next commands will work on your world.
    usage: /<command>
    permissions: groupmanager.manclear