xmpp:
  servicename: 'example.com'
  user: 'name'
  password: 'password'
#  host: 'xmpp.example.com'
#  port: 5222

debug: false

op-users:
#  - 'name@example.com'


log-enabled: false
# Level is minimum level that should be send: info, warning, severe
log-level: warning
log-users:
#  - 'name@example.com'