xmpp:
  server: 'example.com'
  user: 'name@example.com'
  password: 'password'
#  servicename: 'example.com'
#  port: 5222
#  sasl-enabled: false

debug: false

op-users:
#  - 'name@example.com'

# vcard:
#  send: true
#  nickname: 'My Minecraft Server - Survival'
#  emailaddress: 'email@domain.com'
#  organization: 'Creepers Inc. - We are hiring'
#  street: '5555 TNT Lane'
#  city: 'Somewhere'
#  state: 'CA'
#  country: 'USA'

log-enabled: false
# Level is minimum level that should be send: info, warning, severe
log-level: warning
log-users:
#  - 'name@example.com'
