name: EssentialsAntiCheat
main: com.earth2me.essentials.anticheat.NoCheat
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${build.number}
website: http://tiny.cc/EssentialsWiki
description: Detect and Fight the exploitation of various Flaws/Bugs in Minecraft.
authors: [Evenprime, md_5]
commands:
  nocheat:
    description: NoCheat command(s)
    permission: nocheat.admin.commands
    usage: |
           /<command> permlist player [permission]: list NoCheat permissions of player, optionally only if beginning with [permission]
           /<command> playerinfo player: show the collected data NoCheat collected about a player
           /<command> reload: fast reload of NoCheats configuration file(s) - needs additional permissions

permissions:
  nocheat:
    description: Allow a player to bypass all checks and give him all admin permissions
    children:
      nocheat.admin:
        description: Give a player all admin rights
        children:
          nocheat.admin.chatlog:
            description: Player can see NoCheats log messages in the ingame chat
          nocheat.admin.commands:
            description: allow use of the "nocheat" commands (may be given to players to allow them to check statistics)
          nocheat.admin.reload:
            description: allow access to the special "nocheat reload" command (only intended for the actual server administrator)
      nocheat.mod.all:
        description: Various simple cheat mods which they player may or may not be allowed to use
        children:
          nocheat.mod.zombes.fly:
            description: Allow the use of the Zombes fly hack
          nocheat.mod.zombes.cheat:
            description: Allow the use of the Zombes cheat hack, includes xray
          nocheat.mod.cjb.fly:
            description: Allow the use of CJB's fly hack
          nocheat.mod.cjb.xray:
            description: Allow the use of CJB's xray
          nocheat.mod.cjb.minimap:
            description: Allow the use of CJB's minimap
      nocheat.checks:
        description: Allow the player to bypass all checks
        children:
          nocheat.checks.moving: 
            description: Allow the player to bypass all moving related checks
            children:
              nocheat.checks.moving.runfly:
                description: Allow a player to move as free and as fast as he wants (ignores flying, swimming and sneaking settings)
              nocheat.checks.moving.flying:
                description: Allow a player to fly, but only within given speed limits (ignores swimming and sneaking settings)
              nocheat.checks.moving.swimming:
                description: Allow a player to move through water without slowdown
              nocheat.checks.moving.sneaking:
                description: Allow a player to sneak without slowdown
              nocheat.checks.moving.nofall:
                description: Allow a player to cheat and not take fall damage at all
              nocheat.checks.moving.morepackets:
                description: Allow a player to send more move-event-packets than normal, causing him to move faster than normal
          nocheat.checks.blockbreak:
            description: Allow the player to bypass all blockbreak checks
            children:
              nocheat.checks.blockbreak.reach:
                description: Allow a player to break blocks at maximum range (about 6-7 blocks, in creative mode unlimited)
              nocheat.checks.blockbreak.direction:
                description: Allow a player to break blocks that are not in front of them
              nocheat.checks.blockbreak.noswing:
                description: Allow a player to break blocks without swinging their arm
          nocheat.checks.blockplace:
            description: Allow the player to bypass all blockplace checks
            children:
              nocheat.checks.blockplace.reach:
                description: Allow a player to place blocks at maximum range (about 6-7 blocks)
              nocheat.checks.blockplace.direction:
                description: Allow a player to place blocks outside their line of view
          nocheat.checks.chat:
            description: Allow the player to bypass all chat checks
            children:
              nocheat.checks.chat.spam:
                description: Allow a player to send an infinite amount of chat messages
              nocheat.checks.chat.color:
                description: Allow a player to send colored chat messages
          nocheat.checks.fight:
            description: Allow the player to bypass all fight checks
            children:
              nocheat.checks.fight.direction:
                description: Allow a player to attack players and monster even if they are not in his field of view
              nocheat.checks.fight.noswing:
                description: Allow a player to fight without swinging their arm
              nocheat.checks.fight.reach:
                description: Allow a player to fight over bigger distances than usual
              nocheat.checks.fight.speed:
                description: Allow a player to attack faster than usual
              nocheat.checks.fight.godmode:
                description: Allow a player to not take damage by exploiting a design flaw in Minecraft
              nocheat.checks.fight.instantheal:
                description: Allow a player to artificially speed up his health regeneration
          nocheat.checks.inventory:
            description: Allow the player to bypass all inventory checks
            children:
              nocheat.checks.inventory.drop:
                description: Allow a player to drop more items in a short timeframe than the defined limit
              nocheat.checks.inventory.instanteat:
                description: Allow a player to eat food faster than normally possible
              nocheat.checks.inventory.instantbow:
                description: Allow a player to charge his bow faster than usual
