# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: EssentialsGeoIP
main: net.ess3.geoip.EssentialsGeoIP
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${build.number}
website: http://tiny.cc/EssentialsWiki
description: Shows the country or city of a user on login and /whois.
authors: [Essentialsteam, "http://contributors.ess3.net"]
depend: [Essentials-3]